name: Lastest JDemetra+ snapshot

on: [ workflow_dispatch ]

jobs:
  snapshot-job:
    if: startsWith(github.repository, 'nbbrd/') && startsWith(github.ref, 'refs/heads/main')
    strategy:
      matrix:
        java: [ 17 ]
        os: [ ubuntu-latest ]

    name: Snapshot on main
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'

      - name: Build jdemetra-core v3 snapshots
        run: |
          git clone -b v3.0.0 --single-branch --depth=1 https://github.com/jdemetra/jdemetra-core.git jdemetra-core-v3
          mvn -B install -DskipTests=true -f ./jdemetra-core-v3/pom.xml

      - name: Build jdemetra-app v3 snapshots
        run: |
          git clone -b v3.0.0 --single-branch --depth=1 https://github.com/jdemetra/jdemetra-app.git jdemetra-app-v3
          mvn -B install -DskipTests=true -f ./jdemetra-app-v3/pom.xml

      - name: Create pre-release and upload assets
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prerelease: true
          overwrite: true
          draft: false
          file: 'jdemetra-app-v3/demetra-desktop-app/target/jdemetra-*-bin.zip'
