name: JDemetra+ v3 latest snapshot

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  snapshot-job:
    if: startsWith(github.repository, 'nbbrd/') && startsWith(github.ref, 'refs/heads/main')
    strategy:
      matrix:
        java: [ 17 ]
        os: [ ubuntu-latest ]

    name: Snapshot on main
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'

      - name: Create assets
        run: |
          mvn -B -ntp clean package

      - name: Setup Timestamp
        run: echo "timestamp=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Add timestamp to assets names
        run: |
          mv ./target/dependency/jdplus-main-desktop-bin-3.0.0-SNAPSHOT.zip "jdemetra-3.0.0-SNAPSHOT+${{env.timestamp}}-bin.zip"
          mv ./target/dependency/jdplus-main-desktop-bin-3.0.0-SNAPSHOT-windows.zip "jdemetra-3.0.0-SNAPSHOT+${{env.timestamp}}-bin-windows.zip"

      - name: Create release and upload assets
        uses: ncipollo/release-action@v1
        with:
          name: ${{ github.workflow }}
          bodyFile: 'README.md'
          allowUpdates: true
          tag: 'latest'
          removeArtifacts: true
          artifacts: './jdemetra-*-bin*.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
