name: JDemetra+ latest snapshot

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  snapshot-job:
    if: startsWith(github.repository, 'nbbrd/') && startsWith(github.ref, 'refs/heads/main')
    strategy:
      matrix:
        java: [ 17 ]
        os: [ ubuntu-latest ]

    name: Snapshot on main
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'

      - name: Setup Timestamp
        run: | 
          timestamp=$(date +%Y%m%d%H%M%S)
          echo "$timestamp"

      - name: Download Windows JRE
        run: curl -sSL https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.6%2B10/OpenJDK17U-jre_x64_windows_hotspot_17.0.6_10.zip -o jre.zip

      - name: Build jd3-main snapshots
        run: |
          git clone -b develop --single-branch --depth=1 https://github.com/jdemetra/jd3-main.git jd3-main
          mvn -B install -Pfast-build -DskipTests -T1C -f ./jd3-main/pom.xml

      - name: Create asset with bundled Windows JRE
        run: |
          unzip ./jre.zip -d ./jd3-main/jd3-main-desktop/jd3-main-desktop-bin/target/nbdemetra
          pushd ./jd3-main/jd3-main-desktop/jd3-main-desktop-bin/target
          echo "jdkhome=jdk-17.0.6+10-jre" >> etc/nbdemetra.conf
          zip -r ./jdemetra-3.0.0-SNAPSHOT+${timestamp}-bin-windows.zip nbdemetra
          popd

      - name: Add timestamp to main asset name
        run: |
          mv ./jd3-main/jd3-main-desktop/jd3-main-desktop-bin/target/jdemetra-3.0.0-SNAPSHOT-bin.zip "jdemetra-3.0.0-SNAPSHOT+${timestamp}-bin.zip"

      - name: Create release and upload assets
        uses: ncipollo/release-action@v1
        with:
          name: ${{ github.workflow }}
          bodyFile: 'README.md'
          allowUpdates: true
          tag: 'latest'
          removeArtifacts: true
          artifacts: './jdemetra-*-bin*.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
