name: JDemetra+ v3 latest snapshot

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

env:
  MAVEN_ARGS: "-B -ntp"

jobs:
  snapshot-job:
    if: startsWith(github.repository, 'nbbrd/') && startsWith(github.ref, 'refs/heads/main')
    strategy:
      matrix:
        java: [ 21 ]
        os: [ ubuntu-latest ]

    name: Snapshot on main
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout and Setup Maven
        uses: s4u/setup-maven-action@v1.18.0
        with:
          checkout-submodules: true
          checkout-fetch-depth: 0
          java-version: ${{ matrix.java }}

      - name: Create assets
        run: |
          mvn clean package

      - name: Create release and upload assets
        uses: ncipollo/release-action@v1
        with:
          name: ${{ github.workflow }}
          bodyFile: 'README.md'
          allowUpdates: true
          tag: 'latest'
          removeArtifacts: true
          artifacts: './target/upload/*'
          token: ${{ secrets.GITHUB_TOKEN }}
