name: JDemetra+ latest snapshot

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  snapshot-job:
    if: startsWith(github.repository, 'nbbrd/') && startsWith(github.ref, 'refs/heads/main')
    strategy:
      matrix:
        java: [ 17 ]
        os: [ ubuntu-latest ]

    name: Snapshot on main
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'

      - name: Build jd3-main snapshots
        run: |
          git clone -b develop --single-branch --depth=1 https://github.com/jdemetra/jd3-main.git jd3-main
          mvn -B install -Pfast-build -DskipTests -T1C -f ./jd3-main/pom.xml

      - name: Add timestamp to main asset name
        run: |
          mv ./jd3-main/jd3-main-desktop/jd3-main-desktop-bin/target/jdemetra-3.0.0-SNAPSHOT-bin.zip "jdemetra-3.0.0-SNAPSHOT+$(date +%Y%m%d%H%M%S)-bin.zip"

      - name: Create release and upload assets
        uses: ncipollo/release-action@v1
        with:
          name: ${{ github.workflow }}
          bodyFile: 'README.md'
          allowUpdates: true
          tag: 'latest'
          removeArtifacts: true
          artifacts: './jdemetra-*-bin.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
