name: JDemetra+ v3 latest snapshot

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  snapshot-job:
    if: startsWith(github.repository, 'nbbrd/') && startsWith(github.ref, 'refs/heads/main')
    strategy:
      matrix:
        java: [ 17 ]
        os: [ ubuntu-latest ]

    name: Snapshot on main
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'

      - name: Download jdplus-main snapshots
        run: |
          mvn -B -ntp dependency:get -Dartifact=eu.europa.ec.joinup.sat:jdplus-main-desktop-bin:3.0.0-SNAPSHOT:zip -Dtransitive=false -DremoteRepositories=https://oss.sonatype.org/content/repositories/snapshots/
          mvn -B -ntp dependency:copy -Dartifact=eu.europa.ec.joinup.sat:jdplus-main-desktop-bin:3.0.0-SNAPSHOT:zip -Dproject.basedir=.
          mvn -B -ntp dependency:unpack -Dartifact=eu.europa.ec.joinup.sat:jdplus-main-desktop-bin:3.0.0-SNAPSHOT:zip -Dproject.basedir=.

      - name: Create asset with bundled Windows JRE
        run: |
          pushd ./target/dependency
          curl -sSL https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.6%2B10/OpenJDK17U-jre_x64_windows_hotspot_17.0.6_10.zip -o jre-windows.zip
          unzip jre-windows.zip -d nbdemetra
          echo "jdkhome=jdk-17.0.6+10-jre" >> nbdemetra/etc/nbdemetra.conf
          zip -r jdplus-main-desktop-bin-3.0.0-SNAPSHOT-windows.zip nbdemetra
          popd

      - name: Setup Timestamp
        run: echo "timestamp=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Add timestamp to assets names
        run: |
          mv ./target/dependency/jdplus-main-desktop-bin-3.0.0-SNAPSHOT.zip "jdemetra-3.0.0-SNAPSHOT+${{env.timestamp}}-bin.zip"
          mv ./target/dependency/jdplus-main-desktop-bin-3.0.0-SNAPSHOT-windows.zip "jdemetra-3.0.0-SNAPSHOT+${{env.timestamp}}-bin-windows.zip"

      - name: Create release and upload assets
        uses: ncipollo/release-action@v1
        with:
          name: ${{ github.workflow }}
          bodyFile: 'README.md'
          allowUpdates: true
          tag: 'latest'
          removeArtifacts: true
          artifacts: './jdemetra-*-bin*.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
